= User guide

This is the user guide. In this setup, we will automatically install and configure the operators. After that, we will run an example.

Reminder: You can assume that **everything running in the trustee-operator-sysem namespace should run in a trusted, separate environment**. Because of the limitations of this ARO workshop, it is not possible to set up two clusters.

[#user-credentials]
== Setting up the environment

. Go into the terminal on the right and run the following commands:
* Log into azure CLI: `az login --service-principal --username={azure_service_principal_id} --password={azure_service_principal_password} --tenant={azure_tenant_id}`
* Export the `AZURE_RESOURCE_GROUP` variable. It will needed when setting up the operator:
`export AZURE_RESOURCE_GROUP={azure_resource_group}`

. If you need to use the web UI (not necessary in this workshop):
* Navigate to the {aro_console}[Openshift Console, window=blank]
* Login as administrator:
** *Username:* {aro_kube_username}
** *Password:* {aro_kube_password}

[#install]
== Automatically set up the environment

All you need to do is download this script, and let it run till it finishes.

The following scripts sets everything just as in the xref:index-admin.adoc[admin guide], with the following:

* Container signature policy accepts any signed/unsigned image. Refer xref:02-configure-trustee.adoc#trustee-cisvp[here] if you want to change it.
* `INITDATA` allows logs, but disallows generic exec. The only command available in exec are `curl` for `kbsres1` keys, to run the `hello-openshift` example. Refer xref:02-configure-trustee.adoc#trustee-ip[here] if you want to change `INITDATA` and remember to update PCR8 in the xref:02-configure-trustee.adoc#trustee-refval[reference values].
* Trustee already has the necessary keys to run all the next examples. Refer xref:02-configure-trustee.adoc#trustee-key[here] if you want to change Trustee secrets or add new ones.
* CoCo CVM root disk size is `10`. Refer xref:02-configure-osc.adoc#pp-cm[here (ROOT_VOLUME_SIZE)] to change it. Minimum has to be `6`. Remember to restart the `osc-caa-ds` Daemonset after changing it (look at the note at the bottom of the same section)

[source,sh,role=execute]
----
curl -L https://raw.githubusercontent.com/confidential-devhub/workshop-on-ARO-showroom/refs/heads/main/helpers/configure.sh -o configure.sh

chmod +x configure.sh

./configure.sh
----


Now that the configuration is complete, let's run some example!