= Install the Trustee operator

IMPORTANT: In this workshop, we will install Trustee in the **same cluster** that hosts OSC and therefore Confidential Containers. **This is not a suitable solution for production environments.**
Because the Trustee operator contains the refernce values and secrets that are necessary to enstablish the if a Confidential Container is running in a truly safe environment, it should be installed in a separate cluster running in a trusted environment (on prem, for example). Because of the limitations of this ARO workshop, it is not possible to set up two clusters. You can assume that **everything running in the trustee-operator-system namespace should run in a trusted, separate environment**.

Let's start with installing Trustee and setting it up.

[#tcmdline]
== Install via command line

[source,sh,role=execute]
----
oc apply -f-<<EOF
---
apiVersion: v1
kind: Namespace
metadata:
  name: trustee-operator-system
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: trustee-operator-group
  namespace: trustee-operator-system
spec:
  targetNamespaces:
  - trustee-operator-system
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: trustee-operator
  namespace: trustee-operator-system
spec:
  channel: stable
  installPlanApproval: Automatic
  name: trustee-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
EOF
----

=== Verification
Ensure that the Operator is correctly installed by running the following command and checking that the `PHASE` is in `Succeeded` state:
[source,sh,role=execute]
----
watch oc get csv -n trustee-operator-system
----

**Example output**
[source,texinfo,subs="attributes"]
----
NAME                      DISPLAY                            VERSION   REPLACES   PHASE
trustee-operator.v0.4.1   confidential compute attestation   0.4.1                Succeeded
----

