= {lab_name}

This is the user guide. In this setup, we will automatically install and configure the operators. After that, we will run an example.

[#credentials]
== Setting up the environment

. Go into the terminal on the right and run the following commands:
* Log into azure CLI: `az login --service-principal --username={azure_service_principal_id} --password={azure_service_principal_password} --tenant={azure_tenant_id}`
* Export the `AZURE_RESOURCE_GROUP` variable. It will needed when setting up the operator:
`export AZURE_RESOURCE_GROUP={azure_resource_group}`

. If you need to use the web UI (not necessary in this workshop):
* Navigate to the {aro_console}[Openshift Console, window=blank]
* Login as administrator:
** *Username:* {aro_kube_username}
** *Password:* {aro_kube_password}

[#install]
== Automatically set up the environment

All you need to do is download this script, and let it run till it finishes.

The following scripts sets everything just as in the xref:admin::index.adoc[admin guide], with the exception that the **container signature policy accepts any image**.

[source,sh,role=execute]
----
curl -L https://raw.githubusercontent.com/confidential-devhub/workshop-on-ARO-showroom/refs/heads/main/helpers/configure.sh -o configure.sh

chmod +x configure.sh

./configure.sh
----


Now that the configuration is complete, let's run some example!